export const SampleObjects = [
    { userId: 1, id: 1, title: 'delectus aut autem', status: 0, modalImage: true,  subtext: false },
    { userId: 1, id: 2, title: 'quis ut nam facilis et officia qui', status: 1, modalImage: false ,  subtext: true},
    { userId: 1, id: 3, title: 'fugiat veniam minus', status: 2, modalImage: true ,  subtext: false},
    { userId: 1, id: 4, title: 'et porro tempora', status: 0, modalImage: false,  subtext: false},
    { userId: 1, id: 5, title: 'laboriosam mollitia et enim quasi adipisci quia provident illum', status: 1 , modalImage: false,  subtext: true},
    { userId: 1, id: 6, title: 'qui ullam ratione quibusdam voluptatem quia omnis', status: 2 , modalImage: true,  subtext: false},
    { userId: 1, id: 7, title: 'illo expedita consequatur quia in', status: 0 , modalImage: false,  subtext: false},
    { userId: 1, id: 8, title: 'quo adipisci enim quam ut ab', status: 1, modalImage: false,  subtext: true },
    { userId: 1, id: 9, title: 'molestiae perspiciatis ipsa', status: 2, modalImage: true ,  subtext: false},
    { userId: 1, id: 10, title: 'illo est ratione doloremque quia maiores aut', status: 0 , modalImage: false,  subtext: false},
    { userId: 1, id: 11, title: 'vero rerum temporibus dolor', status: 1 , modalImage: false,  subtext: true},
    { userId: 1, id: 12, title: 'ipsa repellendus fugit nisi', status: 2 , modalImage: true,  subtext: false},
    { userId: 1, id: 13, title: 'et doloremque nulla', status: 0 , modalImage: false,  subtext: false},
    { userId: 1, id: 14, title: 'repellendus sunt dolores architecto voluptatum', status: 1 , modalImage: false,  subtext: true},
    { userId: 1, id: 15, title: 'ab voluptatum amet voluptas', status: 2 , modalImage: true,  subtext: false},
    { userId: 1, id: 16, title: 'accusamus eos facilis sint et aut voluptatem', status: 0 , modalImage: false,  subtext: false},
    { userId: 1, id: 17, title: 'quo laboriosam deleniti aut qui', status: 1 , modalImage: false,  subtext: true},
    { userId: 1, id: 18, title: 'dolorum est consequatur ea mollitia in culpa', status: 2 , modalImage: true,  subtext: false},
    { userId: 1, id: 19, title: 'molestiae ipsa aut voluptatibus pariatur dolor nihil', status: 0 , modalImage: false,  subtext: false},
    { userId: 1, id: 20, title: 'ullam nobis libero sapiente ad optio sint', status: 1 , modalImage: false,  subtext: true},
  ];
  